server:
  port: 8888


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basketball?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: wwh325
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:com/neuedu/mapper/*.xml


logging:
  level:
    com:
      neuedu:
        mapper: debug




